version: "3"
services:
  mongo:
    image: mongo:3.4
  ip-app:
    image: bogdanjava/ip-app:1.0.1
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
    - 7776:7777
    networks:
    - mynet
networks:
  mynet: