version: "3"
services:
  ip-app:
    image: bogdanjava/ip-app:1.0.0
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
    - 7776:7777
    networks:
    - mynet
networks:
  mynet: